
@contentType = application/json

### 用户登录
# @name login
POST http://127.0.0.1:8099/v1/user/login HTTP/1.1
content-type: {{contentType}}

{
    "phone": "123456",
    "password": "123456"
}

@token={{login.response.body.$.data.token }}

### 用户详情
POST http://127.0.0.1:8099/v1/user/detail HTTP/1.1
Content-Type: {{contentType}}

{
    "token": "{{token}}"
}


### 
GET http://127.0.0.1:8099/redis/test?type=set HTTP/1.1
Content-Type: {{contentType}}

### 
GET http://127.0.0.1:8099/redis/test?type=get HTTP/1.1
Content-Type: {{contentType}}
