
@contentType = application/json

### 用户登录
# @name login
POST http://127.0.0.1:8099/v1/user/login HTTP/1.1
content-type: {{contentType}}

{
    "phone": "123456",
    "password": "123456"
}

@token={{login.response.body.$.data.token }}

### 用户详情
POST http://127.0.0.1:8099/v1/user/detail HTTP/1.1
Content-Type: {{contentType}}

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDYzMDc3ODIsImlhdCI6MTY0NjI5Njk4MiwiaXNzIjoiemhlbmdwYW5vbmUiLCJVaWQiOjR9.U3_ImyXwYZ__efEWX3KBJNYyWQOIf9MkpC5fNegsk54"
}