basePath: /
definitions:
  request.AddMenu:
    properties:
      menuType:
        description: 菜单类型,1:目录 2:菜单 3:按钮
        type: integer
      name:
        description: 菜单名称
        type: string
      permission:
        description: 菜单权限标识
        type: string
      sort:
        description: 菜单排序
        type: integer
    required:
    - menuType
    - name
    type: object
  request.LoginParam:
    properties:
      captcha:
        description: 验证码
        type: string
      captchaID:
        description: 验证码ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  request.PageInfo:
    properties:
      keyword:
        description: 关键字
        type: string
      page:
        description: 页码
        type: integer
      pageSize:
        description: 每页大小
        type: integer
    type: object
  request.RegisterParam:
    properties:
      address:
        description: 地址
        type: string
      birthday:
        description: 生日
        type: string
      email:
        description: 邮箱
        type: string
      nickName:
        description: 昵称
        maxLength: 32
        minLength: 3
        type: string
      password:
        description: 明文加密后的密码
        type: string
      phone:
        description: 手机号码
        type: string
      roleID:
        type: string
      username:
        description: 用户名
        type: string
    required:
    - nickName
    - password
    - phone
    - username
    type: object
  request.RoleParam:
    properties:
      parentCode:
        description: 父角色Code
        type: string
      roleCode:
        description: 角色code
        type: string
      roleDesc:
        description: 备注
        type: string
      roleName:
        description: 角色名
        type: string
    required:
    - roleCode
    - roleName
    type: object
  response.Meta:
    properties:
      request_id:
        type: string
    type: object
  response.PageResult:
    properties:
      list: {}
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  response.Response:
    properties:
      code:
        description: 业务状态码
        type: integer
      data:
        description: 响应数据
      meta:
        allOf:
        - $ref: '#/definitions/response.Meta'
        description: Meta 源数据,存储如请求ID,分页等信息
      msg:
        description: 提示信息
        type: string
    type: object
  response.SysCaptchaResponse:
    properties:
      captcha_id:
        type: string
      captcha_length:
        type: integer
      pic_path:
        type: string
    type: object
  system.Meta:
    properties:
      activeName:
        type: string
      closeTab:
        description: 自动关闭tab
        type: boolean
      defaultMenu:
        description: 是否是基础路由（开发中）
        type: boolean
      icon:
        description: 菜单图标
        type: string
      keepAlive:
        description: 是否缓存
        type: boolean
      title:
        description: 菜单名
        type: string
    type: object
  system.SysAuthority:
    properties:
      UpdateAt:
        description: 使用时间戳毫秒数填充更新时间
        type: string
      authorityId:
        description: 角色ID
        type: integer
      authorityName:
        description: 角色名
        type: string
      children:
        items:
          $ref: '#/definitions/system.SysAuthority'
        type: array
      createAt:
        description: 使用时间戳秒数填充创建时间
        type: string
      dataAuthorityId:
        items:
          $ref: '#/definitions/system.SysAuthority'
        type: array
      defaultRouter:
        description: 默认菜单(默认dashboard)
        type: string
      menus:
        items:
          $ref: '#/definitions/system.SysMenu'
        type: array
      parentId:
        description: 父角色ID
        type: integer
    type: object
  system.SysBaseMenuBtn:
    properties:
      UpdateAt:
        description: 使用时间戳毫秒数填充更新时间
        type: string
      createAt:
        description: 使用时间戳秒数填充创建时间
        type: string
      desc:
        type: string
      name:
        type: string
      sysBaseMenuID:
        type: integer
    type: object
  system.SysMenu:
    properties:
      ID:
        description: 主键ID
        type: integer
      UpdateAt:
        description: 使用时间戳毫秒数填充更新时间
        type: string
      children:
        items:
          $ref: '#/definitions/system.SysMenu'
        type: array
      component:
        type: string
      createAt:
        description: 使用时间戳秒数填充创建时间
        type: string
      icon:
        type: string
      menuBtn:
        items:
          $ref: '#/definitions/system.SysBaseMenuBtn'
        type: array
      menuType:
        type: integer
      meta:
        $ref: '#/definitions/system.Meta'
      name:
        type: string
      parameters:
        items:
          $ref: '#/definitions/system.SysMenuParameter'
        type: array
      parentId:
        type: integer
      path:
        type: string
      permission:
        type: string
      sort:
        type: integer
      visible:
        type: boolean
    type: object
  system.SysMenuParameter:
    properties:
      UpdateAt:
        description: 使用时间戳毫秒数填充更新时间
        type: string
      createAt:
        description: 使用时间戳秒数填充创建时间
        type: string
      key:
        description: 地址栏携带参数的key
        type: string
      sysBaseMenuID:
        type: integer
      type:
        description: 地址栏携带参数为params还是query
        type: string
      value:
        description: 地址栏携带参数的值
        type: string
    type: object
  system.SysUser:
    properties:
      ID:
        description: 主键ID
        type: integer
      UpdateAt:
        description: 使用时间戳毫秒数填充更新时间
        type: string
      activeColor:
        description: 活跃颜色
        type: string
      authorities:
        items:
          $ref: '#/definitions/system.SysAuthority'
        type: array
      authority:
        allOf:
        - $ref: '#/definitions/system.SysAuthority'
        description: '`gorm:"foreignKey:关联表的结构体字段;references:当前表的结构体字段;`'
      authorityId:
        description: 用户角色ID
        type: integer
      baseColor:
        description: 基础颜色
        type: string
      createAt:
        description: 使用时间戳秒数填充创建时间
        type: string
      email:
        description: 用户邮箱
        type: string
      enable:
        description: 用户是否被冻结 1正常 2冻结
        type: integer
      headerImg:
        description: 用户头像
        type: string
      nickName:
        description: 用户昵称
        type: string
      phone:
        description: 用户手机号
        type: string
      sex:
        enum:
        - female
        - male
        type: string
      sideMode:
        description: 用户侧边主题
        type: string
      status:
        type: string
      token:
        type: string
      userInfo:
        $ref: '#/definitions/system.SysUserInfo'
      userName:
        description: 用户登录名
        type: string
      uuid:
        description: 用户UUID
        type: string
    type: object
  system.SysUserInfo:
    properties:
      ID:
        description: 主键ID
        type: integer
      UpdateAt:
        description: 使用时间戳毫秒数填充更新时间
        type: string
      address:
        type: string
      birthday:
        type: string
      createAt:
        description: 使用时间戳秒数填充创建时间
        type: string
      userID:
        type: string
    type: object
info:
  contact:
    name: go-swagger帮助文档
    url: https://github.com/swaggo/swag/blob/master/README_zh-CN.md
  description: This is gin learn api docs.
  license:
    name: Apache 2.0
  title: gin swagger API接口文档
  version: 0.0.1
paths:
  /user/getUserList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 页码, 每页大小
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 分页获取用户列表,返回包括列表,总数,页码,每页数量
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取用户列表
      tags:
      - SysUser
  /user/setUserInfo:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID, 用户名, 昵称, 头像链接
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/system.SysUser'
      produces:
      - application/json
      responses:
        "200":
          description: 设置用户信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  additionalProperties: true
                  type: object
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 设置用户信息
      tags:
      - SysUser
  /v1/api/admin/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      operationId: /v1/api/admin/login
      parameters:
      - description: 用户名,密码,验证码,验证码ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户登录
      tags:
      - 登陆注册
  /v1/api/admin/logout:
    post:
      consumes:
      - application/json
      description: 退出登录
      operationId: /v1/api/admin/logout
      parameters:
      - description: 用户名,密码,验证码,验证码ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginParam'
      produces:
      - application/json
      responses: {}
      summary: 用户退出
      tags:
      - 登陆注册
  /v1/api/admin/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      operationId: /v1/api/admin/register
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterParam'
      produces:
      - application/json
      responses: {}
      summary: 用户注册
      tags:
      - 登陆注册
  /v1/api/captcha:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 生成验证码,返回包括随机数id,base64,验证码长度
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.SysCaptchaResponse'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 生成验证码
      tags:
      - 登陆注册
  /v1/api/changePassword:
    post:
      consumes:
      - application/json
      description: 更改密码
      operationId: /v1/user/changePassword
      produces:
      - application/json
      responses: {}
      summary: 更改密码
      tags:
      - 登陆注册
  /v1/api/config:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 获取配置
      tags:
      - Base
  /v1/api/jwt/jsonInBlacklist:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: jwt加入黑名单
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: jwt加入黑名单
      tags:
      - Jwt
  /v1/api/menu/addMenu:
    post:
      consumes:
      - application/json
      parameters:
      - description: 路由path, 父菜单ID, 路由name, 对应前端文件路径, 排序标记
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AddMenu'
      produces:
      - application/json
      responses:
        "200":
          description: 新增菜单
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 新增菜单
      tags:
      - 菜单管理
  /v1/api/menu/getMenuList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 页码, 每页大小
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 分页获取基础menu列表,返回包括列表,总数,页码,每页数量
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取基础menu列表
      tags:
      - Menu
  /v1/api/role/addRole:
    post:
      consumes:
      - application/json
      description: 创建角色
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RoleParam'
      produces:
      - application/json
      responses: {}
      summary: 创建角色
      tags:
      - 角色管理
  /v1/api/role/delete/:id:
    delete:
      consumes:
      - application/json
      description: 删除角色
      parameters:
      - description: 角色ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除角色
      tags:
      - 角色管理
  /v1/api/role/pageRole:
    post:
      consumes:
      - application/json
      description: 分页获取角色
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses: {}
      summary: 分页获取角色
      tags:
      - 角色管理
  /v1/api/role/update:
    put:
      consumes:
      - application/json
      description: update role
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses: {}
      summary: 更新角色
      tags:
      - 角色管理
swagger: "2.0"
