@contentType = application/json

### 获取图片验证码
GET http://127.0.0.1:8099/v1/api/admin/captcha HTTP/1.1


### 用户注册
POST http://127.0.0.1:8099/v1/user/register HTTP/1.1
content-type: {{contentType}}

{
"username":"zhangsan",
"password":"123456"
}

### 用户登录
# @name login
POST http://127.0.0.1:8099/v1/user/login HTTP/1.1
content-type: {{contentType}}

{
    "username": "zhangsan",
    "password": "12345"
}

@token={{login.response.body.$.data.token }}

### 用户详情
POST http://127.0.0.1:8099/v1/user/detail HTTP/1.1
Content-Type: {{contentType}}

{
    "token": "{{token}}"
}


### 
GET http://127.0.0.1:8099/redis/test?type=set HTTP/1.1
Content-Type: {{contentType}}

### 
GET http://127.0.0.1:8099/redis/test?type=get HTTP/1.1
Content-Type: {{contentType}}
