version: "3"
services:
  mysql:
    image: mysql:8.0.21    # 如果您是 arm64 架构：如 MacOS 的 M1，请修改镜像为 image: mysql/mysql-server:8.0.21
    container_name: gva-mysql
    hostname: gva-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "3306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # root管理员用户密码
      MYSQL_DATABASE: 'gin-vue3-admin' # 初始化启动时要创建的数据库的名称
      #MYSQL_USER: 'zhengpanone'
      # MYSQL_PASSWORD: '123456'
    volumes:
      - ./mysql:/var/lib/mysql
    # networks:
    #   network:
    #     ipv4_address: 177.7.0.13
